on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Render GIFs
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-node@main

      - run: sudo apt update

      - run: sudo apt install ffmpeg

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install

      - name: Render Video
        uses: borales/actions-yarn@v5
        with:
          cmd: render

      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update gifs"
